seed = 0
function = "bin.xgboost_.main"
n_trials = 100
timeout = "__null__"

[sampler]

[space]
seed = 0

[space.data]
seed = 0
path = "data/california"
num_policy = "__null__"
cat_policy = "__null__"
y_policy = "standard"
cache = true

[space.fit]
early_stopping_rounds = 50
verbose = true

[space.model]
tree_method = "gpu_hist"
use_label_encoder = false
colsample_bytree = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]
gamma = [
    "_tune_",
    "?loguniform",
    0,
    0.001,
    100.0,
]
lambda = [
    "_tune_",
    "?loguniform",
    0.0,
    0.1,
    10.0,
]
learning_rate = [
    "_tune_",
    "loguniform",
    0.001,
    1.0,
]
max_depth = [
    "_tune_",
    "int",
    3,
    10,
]
min_child_weight = [
    "_tune_",
    "loguniform",
    0.0001,
    100.0,
]
subsample = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]
